"""Bounded concurrency and deadline primitives for the single-process runtime."""

from rag_mvp.performance.admission import (
    AdmissionClosedError,
    AdmissionLease,
    AdmissionRejectedError,
    AdmissionSnapshot,
    QAAdmissionController,
)
from rag_mvp.performance.deadlines import (
    DeadlineController,
    DeadlineExceededError,
    OptionalStageResult,
    QALatencyBudgets,
    StageDeadlineExceededError,
)
from rag_mvp.performance.evidence_bundle import (
    EVIDENCE_SCHEMA_URI,
    EVIDENCE_SCHEMA_VERSION,
    EvidenceSerializationError,
    EvidenceValidationError,
    EvidenceWriteError,
    PerformanceCostEvidence,
    PerformanceEvidenceIdentity,
    PerformanceEvidenceReferences,
    PerformanceRateEvidence,
    build_performance_evidence_bundle,
    load_performance_evidence_bundle,
    validate_performance_evidence_bundle,
    write_performance_evidence_bundle,
)
from rag_mvp.performance.load_report import (
    ACCEPTANCE_CONCURRENCY,
    ERROR_RATE_THRESHOLD,
    MINIMUM_SUCCESSFUL_REQUESTS,
    P90_LATENCY_THRESHOLD_MS,
    LatencySummary,
    LoadAcceptanceThresholds,
    LoadAttempt,
    LoadAttemptStatus,
    LoadReport,
    WarmupSummary,
    build_load_report,
    nearest_rank_percentile,
)
from rag_mvp.performance.load_test import (
    HttpLoadTestConfig,
    HttpLoadTestHarness,
    LoadScenario,
    parse_qa_response,
)
from rag_mvp.performance.pricing import (
    PerformancePricingEvidence,
    PerformanceRolePricing,
    calculate_performance_cost,
)
from rag_mvp.performance.worker_pools import (
    BoundedWorkerPool,
    RagWorkerPools,
    WorkerPoolClosedError,
    WorkerPoolLimits,
    WorkerPoolSaturatedError,
)

__all__ = [
    "ACCEPTANCE_CONCURRENCY",
    "ERROR_RATE_THRESHOLD",
    "EVIDENCE_SCHEMA_URI",
    "EVIDENCE_SCHEMA_VERSION",
    "MINIMUM_SUCCESSFUL_REQUESTS",
    "P90_LATENCY_THRESHOLD_MS",
    "AdmissionClosedError",
    "AdmissionLease",
    "AdmissionRejectedError",
    "AdmissionSnapshot",
    "BoundedWorkerPool",
    "DeadlineController",
    "DeadlineExceededError",
    "EvidenceSerializationError",
    "EvidenceValidationError",
    "EvidenceWriteError",
    "HttpLoadTestConfig",
    "HttpLoadTestHarness",
    "LatencySummary",
    "LoadAcceptanceThresholds",
    "LoadAttempt",
    "LoadAttemptStatus",
    "LoadReport",
    "LoadScenario",
    "OptionalStageResult",
    "PerformanceCostEvidence",
    "PerformanceEvidenceIdentity",
    "PerformanceEvidenceReferences",
    "PerformancePricingEvidence",
    "PerformanceRateEvidence",
    "PerformanceRolePricing",
    "QAAdmissionController",
    "QALatencyBudgets",
    "RagWorkerPools",
    "StageDeadlineExceededError",
    "WarmupSummary",
    "WorkerPoolClosedError",
    "WorkerPoolLimits",
    "WorkerPoolSaturatedError",
    "build_load_report",
    "build_performance_evidence_bundle",
    "calculate_performance_cost",
    "load_performance_evidence_bundle",
    "nearest_rank_percentile",
    "parse_qa_response",
    "validate_performance_evidence_bundle",
    "write_performance_evidence_bundle",
]
